### ISSUE TITLE
Panning/Rotating while the animation GUI is visible disables scene navigation

### ISSUE THREAD

**Issue by ericraue** [JuhaKiili/RagePixel#14]
I've been tracking down an issue where RagePixel locks out panning and rotating the scene view even when a sprite is not selected. These steps reproduce the bug 100% of the time. The only way to regain control is to reload the project or modify any script file. Even creating/loading another scene file with no RagePixel objects does not fix it. I'm wondering if this is actually a bug with Unity. 
1. Fresh copy of RagePixel
2. Create a new sprite and draw something
3. Click the Transform tool (Arrow)
4. Confirm that you can pan around the scene (CMD/CTRL + Middle Mouse Button)
5. Click the Animation button, the animation bar appears
6. Hold CMD + Middle Mouse Button to pan around the scene
7. Bug: animation frames GUI disappears and the user can no longer pan or rotate the scene view. 

Notes:
- The hand tool in the top left remains selected even when clicking the move/rotate/scale tools
- Selecting a non-RagePixel object does not give you back control
- Loading another scene does not give you back control

There is also a similar bug that prevents the user from panning the screen while drawing. This occurs because the events are consumed before they are sent to Unity. 

I'm looking at these problems now.

**Comment by JuhaKiili** [comment]
My first days here in Unity I've been fixing some random bugs and I think I fixed something like this. It happened when you do something holding your right mouse button down and then you do something with the left button while holding the right one. Happens with custom handles only.

I have no idea when my fix will be on some official release or anything, but try to see if you can reproduce stuff like that.

**Comment by JuhaKiili** [comment]
Oh you closed the issue. Nice.

**Comment by ericraue** [comment]
@JuhaKiili I fixed the issue by consuming Event.current in HandleAnimationGUI but I suspect this didn't really fix the real bug since creating/loading a scene should have been enough to regain control. Not sure if this a Unity bug or a RagePixel bug.
