### ISSUE TITLE
ActionScript Support

### ISSUE THREAD

**Issue by TheNewb** [JuhaKiili/RagePixel#16]
Is there sction script support??

**Comment by ericraue** [comment]
It doesn't officially support it at the moment but it probably should work as is. Create a Plugins folder and move the RagePixel/Code folder into it. 

![Project settings](http://puu.sh/w3SV)

Here's the Player.js file to show that it works.

``` javascript
#pragma strict

function Start () 
{
    var sprite : RagePixelSprite = GetComponent(RagePixelSprite);
    sprite.SetTintColor(Color.black);
}
```

**Comment by TheNewb** [comment]
thanks m8 appreciate it. good work sir and good luck in future realeases.
